# Generated by Django 2.2.6 on 2020-04-13 10:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_auto_20200413_1044'),
        ('accounts', '0002_auto_20200413_1044'),
        ('appliances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplianceBase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(blank=True, max_length=255)),
                ('year', models.CharField(blank=True, max_length=255)),
                ('manufacturer', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='appliance',
            name='active',
        ),
        migrations.AddField(
            model_name='appliance',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='appliance',
            name='building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='buildings.Building'),
        ),
        migrations.AddField(
            model_name='appliance',
            name='appliance_base',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appliances.ApplianceBase'),
        ),
    ]
