# Generated by Django 2.2.6 on 2020-04-13 14:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0002_auto_20200413_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplianceTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_datetime', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('NA', 'Not Available')], default='NA', max_length=2)),
                ('appliance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appliances.Appliance')),
            ],
        ),
    ]
