# Generated by Django 2.2.6 on 2020-04-14 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0003_appliancetransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliance',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='appliancebase',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
