# Generated by Django 2.2.6 on 2020-04-14 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0004_auto_20200414_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliancebase',
            name='brand',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='appliancebase',
            name='manufacturer',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='appliancebase',
            name='model',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='appliancebase',
            name='year',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
