# Generated by Django 2.2.5 on 2020-03-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='employee_type',
            field=models.CharField(choices=[('AR', 'Architect'), ('AN', 'Analyst'), ('DV', 'Developer'), ('NA', 'Not Available')], default='NA', max_length=2),
        ),
    ]
