version: "3"

services:
  app:
    build: .
    container_name: django-zeusapi
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    command:
      "gunicorn --workers=2 --bind=0.0.0.0:8000 zeusapi.wsgi:application"

  redis:
    image: redis:alpine

  celery:
    build: ./project
    command: celery -A core worker -l info
    volumes:
        - ./project/:/usr/src/app/
    environment:
        - DEBUG=1
        - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
        - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
        - CELERY_BROKER=redis://redis:6379/0
        - CELERY_BACKEND=redis://redis:6379/0        
    depends_on:
        - redis

  celery-beat:
    build: ./project
    command: celery -A core beat -l info
    volumes:
        - ./project/:/usr/src/app/
    environment:
        - DEBUG=1
        - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
        - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    depends_on:
        - redis      


        
#####
#
#
#  nginx:
#    image: nginx:1.17
#    container_name: ngx
#    ports:
#      - "5000:8000"
#    volumes:
#      - ./nginx:/etc/nginx/conf.d
#    depends_on:
#      - app
#
#
#####