# Generated by Django 2.2.6 on 2020-04-13 10:44

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(default='NA', max_length=255)),
                ('date_generated', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_invoiced', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_due_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_paid', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
