# Generated by Django 2.2.6 on 2020-04-14 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='date_invoiced',
            new_name='date_invoice_sent',
        ),
        migrations.AddField(
            model_name='bill',
            name='boolean_due_date',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bill',
            name='boolean_generated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='boolean_invoiced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bill',
            name='boolean_paid',
            field=models.BooleanField(default=False),
        ),
    ]
