# Generated by Django 2.2.6 on 2020-04-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aimodels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='aimodel_type',
            field=models.CharField(choices=[('NA', 'Not Available')], default='NA', max_length=2),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='purpose',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='version',
            field=models.CharField(blank=True, default='0.0.1', max_length=255),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
