# Generated by Django 2.2.6 on 2020-04-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='version',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
