# Generated by Django 2.2.6 on 2020-04-14 11:20

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_auto_20200413_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='area',
            field=django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326),
        ),
    ]
