# Generated by Django 2.2.6 on 2020-04-13 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('AR', 'Architect'), ('AN', 'Analyst'), ('DV', 'Developer'), ('NA', 'Not Available')], default='NA', max_length=2),
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(default='NA')),
                ('sent', models.BooleanField(default=False)),
                ('received', models.BooleanField(default=False)),
                ('read', models.BooleanField(default=False)),
                ('sent_datetime', models.DateTimeField(null=True)),
                ('received_datetime', models.DateTimeField(null=True)),
                ('read_datetime', models.DateTimeField(null=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_message_receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_message_sender', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.Ticket')),
            ],
        ),
    ]
