# Generated by Django 2.2.6 on 2020-04-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20200414_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='solved',
            field=models.BooleanField(default=False),
        ),
    ]
